<?php

/**
 * This file generated by Mezzio\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via mezzio-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            App\Handler\HelloHandler::class => App\Handler\HelloHandlerFactory::class,
            App\Handler\UsersExportHandler::class => App\Handler\UsersExportHandlerFactory::class,
            App\Handler\UsersExportMiddleware::class => App\Handler\UsersExportMiddlewareFactory::class,
            App\Handler\UsersImportHandler::class => App\Handler\UsersImportHandlerFactory::class,
            App\Middleware\UsersExportMiddleware::class => App\Middleware\UsersExportMiddlewareFactory::class,
            App\Middleware\UsersImportMiddleware::class => App\Middleware\UsersImportMiddlewareFactory::class,
            App\XClacksOverheadMiddleware::class => App\XClacksOverheadMiddlewareFactory::class,
        ],
    ],
];
